# Generated by Django 3.2.3 on 2021-05-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210524_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post', verbose_name='Картинки')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='posts.post')),
            ],
        ),
    ]
